{
  imports = [
    ./boot.nix
    ./docker.nix
    ./git.nix
    ./hardening.nix
    ./home-manager.nix
    ./htop.nix
    ./impermanence.nix
    ./locale.nix
    ./misc.nix
    ./networking.nix
    ./nix.nix
    ./programs.nix
    ./sops.nix
    ./ssh.nix
    ./user.nix
    ./zsh.nix
  ];
}
